> ### **Assignment 2 - Numpy Array Operations**
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
>
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 .
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions.

- `np.clip()` - Limits the values in an array
- `np.pad()` - Pads an array
- `np.argsort()` - Returns the indices that would sort an array
- `np.linalg.eig()` - Computes the eigenvalues and right eigenvectors of a square matrix
- `np.where()` - Returns elements chosen from `x` and `y` depending on the `condition`

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
# !pip install jovian --upgrade -q

In [2]:
# import jovian

In [3]:
# jovian.commit(project='numpy-array-operations')

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [5]:
# List of functions explained
#function1 = np.clip() # Limits the values in an array
#function2 = np.pad() # Pads an array
#function3 = np.argsort() # Returns the indices that would sort an array
#function4 = np.linalg.eig() # Computes the eigenvalues and right eigenvectors of a square matrix
#function5 = np.where() # Returns elements chosen from `x` or `y` depending on `condition`

## Function 1 - np.clip()

This function is used to limit the values in an array to a given range. Any values below the lower limit will be set to the lower limit, and any values above the upper limit will be set to the upper limit.

In [6]:
# Example 1: Basic usage
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
clipped = np.clip(a, 3, 7)
print("Clipped array:", clipped)

Clipped array: [3 3 3 4 5 6 7 7 7]


Explanation about example

In [7]:
# Example 2: Clipping 2D array
b = np.random.rand(3, 3) * 10  # Random values between 0 and 10
clipped_2d = np.clip(b, 1, 5)
print("Clipped 2D array:\n", clipped_2d)

Clipped 2D array:
 [[4.50199703 4.03105962 5.        ]
 [5.         5.         2.18109305]
 [1.         4.53697626 3.71895571]]


Explanation about example

In [8]:
# Example 3: Using np.clip to handle outliers in data
data = np.random.normal(100, 20, 200)  # Normally distributed data
clipped_data = np.clip(data, 50, 150)
print("Data with outliers handled:", clipped_data[:10])

Data with outliers handled: [ 95.13647719  80.15594344  80.49589518 120.02561588 116.55566416
  99.20243971 100.68642631 124.31249529  87.19299295 114.38093942]


Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [9]:
# jovian.commit()

## Function 2 - np.pad()

This function pads an array with a constant or another form of padding specified by the pad width and mode arguments.

In [10]:
# Example 1: Padding a 1D array
c = np.array([1, 2, 3])
padded_c = np.pad(c, (2, 3), 'constant', constant_values=(4, 6))
print("Padded 1D array:", padded_c)

Padded 1D array: [4 4 1 2 3 6 6 6]


Explanation about example

In [11]:
# Example 2: Padding a 2D array symmetrically
d = np.array([[1, 2], [3, 4]])
padded_d = np.pad(d, pad_width=1, mode='symmetric')
print("Symmetrically padded 2D array:\n", padded_d)

Symmetrically padded 2D array:
 [[1 1 2 2]
 [1 1 2 2]
 [3 3 4 4]
 [3 3 4 4]]


Explanation about example

In [12]:
# Example 3: Edge padding
padded_edge = np.pad(d, pad_width=2, mode='edge')
print("Edge padded 2D array:\n", padded_edge)

Edge padded 2D array:
 [[1 1 1 2 2 2]
 [1 1 1 2 2 2]
 [1 1 1 2 2 2]
 [3 3 3 4 4 4]
 [3 3 3 4 4 4]
 [3 3 3 4 4 4]]


Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [13]:
# jovian.commit()

## Function 3 - np.argsort()

This function returns indices that would sort an array

In [14]:
# Example 1: Basic argsort
e = np.array([3, 1, 2])
sorted_indices = np.argsort(e)
print("Indices of sorted array:", sorted_indices)

Indices of sorted array: [1 2 0]


Explanation about example

In [15]:
# Example 2: Using argsort with 2D array
f = np.random.rand(3, 3) * 10
sorted_indices_2d = np.argsort(f, axis=0)
print("Column-wise sorted indices of 2D array:\n", sorted_indices_2d)

Column-wise sorted indices of 2D array:
 [[0 2 0]
 [1 1 1]
 [2 0 2]]


Explanation about example

In [16]:
# Example 3: Using argsort to sort array based on custom criteria
ages = np.array([25, 30, 20, 50, 40, 35])
weights = np.array([50, 80, 55, 90, 85, 95])
sorted_by_age = np.argsort(ages)
print("Weights sorted by age:", weights[sorted_by_age])

Weights sorted by age: [55 50 80 95 85 90]


Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [17]:
# jovian.commit()

## Function 4 - np.linalg.eig()

This function computes the eigenvalues and right eigenvectors of a square matrix.

In [18]:
# Example 1: Eigenvalues and eigenvectors of a 2x2 matrix
g = np.array([[1, 2], [2, 3]])
eigenvalues, eigenvectors = np.linalg.eig(g)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [-0.23606798  4.23606798]
Eigenvectors:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


Explanation about example

In [19]:
# Example 2: Real symmetric matrix
h = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
eigenvalues_h, eigenvectors_h = np.linalg.eig(h)
print("Eigenvalues of symmetric matrix:", eigenvalues_h)
print("Eigenvectors of symmetric matrix:\n", eigenvectors_h)

Eigenvalues of symmetric matrix: [3.41421356 2.         0.58578644]
Eigenvectors of symmetric matrix:
 [[-5.00000000e-01 -7.07106781e-01  5.00000000e-01]
 [ 7.07106781e-01  4.05405432e-16  7.07106781e-01]
 [-5.00000000e-01  7.07106781e-01  5.00000000e-01]]


Explanation about example

In [20]:
# Example 3: Using eigenvectors for principal component analysis (PCA) simulation
data = np.random.rand(10, 3)  # Simulate some multi-dimensional data
cov_matrix = np.cov(data.T)  # Compute the covariance matrix
e_vals, e_vecs = np.linalg.eig(cov_matrix)  # Get eigenvalues and vectors
print("Eigenvalues for PCA:", e_vals)
print("Eigenvectors for PCA:\n", e_vecs)

Eigenvalues for PCA: [0.14658628 0.07297158 0.04976338]
Eigenvectors for PCA:
 [[-0.54832423 -0.61866735  0.56266442]
 [-0.79006257  0.60378399 -0.10604725]
 [ 0.2741198   0.50268837  0.81985531]]


Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [21]:
# jovian.commit()

## Function 5 - np.where()

It can be used to conditionally select elements from an array, or to create a new array based on conditions. 

In [22]:
# Example 1 - working
# Create an array
array = np.array([1, 2, 3, 6, 7, 8])

# Use np.where to replace all elements < 5 with -1
modified_array = np.where(array < 5, -1, array)
print("Modified Array:", modified_array)

Modified Array: [-1 -1 -1  6  7  8]


In this example, np.where is used to replace all elements in an array that are less than 5 with the number -1.

In [23]:
# Example 2 - working
# Two arrays of the same length
array_x = np.array([10, 20, 30, 40, 50])
array_y = np.array([5, 15, 25, 35, 45])

# Condition array
condition = np.array([True, False, True, False, True])

# Use np.where to select elements from array_x or array_y based on condition
result_array = np.where(condition, array_x, array_y)
print("Result Array:", result_array)


Result Array: [10 15 30 35 50]


In this example, np.where is used to select elements from two arrays based on a condition applied to a third array.

In [24]:
# Example 3 - breaking (to illustrate when it breaks)
# Create an array of integers
data = np.random.randint(1, 100, 10)

# Use np.where to categorize data based on value ranges
categorized_data = np.where(data < 30, "Low",
                            np.where(data < 60, "Medium", "High"))
print("Data:", data)
print("Categorized Data:", categorized_data)


Data: [75 46 73  6 65 81 66 96 58 92]
Categorized Data: ['High' 'Medium' 'High' 'Low' 'High' 'High' 'High' 'High' 'Medium' 'High']


Here, np.where is used to evaluate multiple conditions to generate a new array. This is handy for creating feature columns in data processing or more complex manipulations.

Some closing comments about when to use this function.

In [25]:
# jovian.commit()

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [27]:
# jovian.commit()